# Generated by Django 5.0.1 on 2025-02-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('basicuser', 'Basic User'), ('admin', 'Admin')], default='basicuser', max_length=30),
        ),
    ]
