# Generated by Django 5.1.6 on 2025-02-27 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('latex_template', models.TextField()),
                ('field_schema', models.JSONField(help_text='JSON schema defining form fields')),
                ('required_approvals', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('basicuser', 'Basic User'), ('admin', 'Admin')], default='student', max_length=30),
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(help_text='JSON data containing form field values')),
                ('current_pdf', models.FileField(blank=True, null=True, upload_to='form_pdfs/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('returned', 'Returned for Changes'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.formtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='FormApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('returned', 'Returned for Changes'), ('rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='signed_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_approvals', to=settings.AUTH_USER_MODEL)),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.formsubmission')),
            ],
            options={
                'unique_together': {('form_submission', 'approver', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='FormApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_role', models.CharField(choices=[('basicuser', 'Basic User'), ('admin', 'Admin')], max_length=30)),
                ('order', models.PositiveIntegerField(help_text='Order in the approval sequence')),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals_workflows', to='api.formtemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('form_template', 'order')},
            },
        ),
    ]
