# Generated by Django 5.1.6 on 2025-03-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_formtemplate_user_signature_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='formtemplate',
            name='latex_template',
        ),
        migrations.AddField(
            model_name='formapproval',
            name='signed_pdf_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='pdf_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='formapproval',
            name='signed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='forms/signed_pdfs/'),
        ),
        migrations.AlterField(
            model_name='formapprovalworkflow',
            name='approver_role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=30),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='current_pdf',
            field=models.FileField(blank=True, null=True, upload_to='forms/form_pdfs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('staff', 'Staff')], default='student', max_length=30),
        ),
    ]
