# Generated by Django 5.1.6 on 2025-03-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_formsubmission_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_signature',
            field=models.BooleanField(default=False),
        ),
    ]
