# Generated by Django 5.1.6 on 2025-03-07 05:32

import utils.hash
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_has_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=utils.hash.signature_upload_path),
        ),
    ]
