# Generated by Django 5.1.6 on 2025-04-02 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmissionIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('form_type', models.CharField(max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('form_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_identifier', to='api.formsubmission')),
            ],
            options={
                'indexes': [models.Index(fields=['identifier'], name='api_formsub_identif_e65ef4_idx'), models.Index(fields=['student_id'], name='api_formsub_student_ec4c71_idx')],
            },
        ),
    ]
