# Generated by Django 5.2 on 2025-04-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_formapproval_delegated_by_organizationalunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_id',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
