# Generated by Django 5.2 on 2025-04-20 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_formsubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapproval',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='api.formapprovalworkflow'),
        ),
        migrations.AddField(
            model_name='formapprovalworkflow',
            name='approval_position',
            field=models.CharField(default='N/A', help_text='Position title of the approver', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formapprovalworkflow',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Whether this approval is required for completion'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='completed_approval_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of completed approvals'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='required_approval_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of required approvals for this submission'),
        ),
        migrations.AlterField(
            model_name='formapproval',
            name='decision',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('returned', 'Returned for Changes'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formapprovalworkflow',
            name='order',
            field=models.PositiveIntegerField(help_text='Suggested order in the approval sequence'),
        ),
    ]
