# Generated by Django 5.0.1 on 2025-04-21 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_formapproval_workflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldelegation',
            name='notify_on_approval',
            field=models.BooleanField(default=True, help_text='Notify delegator when delegate makes an approval decision'),
        ),
        migrations.AddField(
            model_name='approvaldelegation',
            name='notify_on_new_request',
            field=models.BooleanField(default=True, help_text='Notify delegate when new approval requests arrive'),
        ),
        migrations.CreateModel(
            name='DelegationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=20)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, help_text='Additional details about the action', null=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegation_actions', to=settings.AUTH_USER_MODEL)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.approvaldelegation')),
            ],
            options={
                'ordering': ['-action_date'],
            },
        ),
    ]
