name: backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - django
  - psycopg2
  - python-dotenv
  - djangorestframework
  - django-cors-headers
  - pip
  - whitenoise=6.4.0
  - wfastcgi=3.0.0
  - python-dotenv
  - colorama=0.4.6
  - drf-spectacular
  - pillow